name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7']
        julia-arch: [x64]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - name: Build package
        id: buildpackage
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project=${{ @. }} -e "using Pkg; Pkg.build(verbose = true)"
      - name: Run tests
        id: runtests
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project=${{ @. }} -e "using Pkg; Pkg.test()" && echo "TESTS_SUCCESSFUL" = true >> $GITHUB_ENV
      